### ISSUE TITLE
multiple ^^^superscripts no longer stack

### ISSUE THREAD

**Issue by ghost** [Lachcim/css-irl-bot#6]
on [.old](https://old.reddit.com/r/css_irl/comments/kprcei/windownthchild_10_transform_rotate_30deg/ghzhwqu/?context=3):
![Screenshot_2021-01-04  window nth-child( 10 ) { transform rotate( 30deg ); transform-origin bottom left }_20210104141636](https://user-images.githubusercontent.com/59403389/103544107-da0d3f80-4e9f-11eb-86a9-2fcb8e04b509.png)

and on [.new](https://new.reddit.com/r/css_irl/comments/kprcei/windownthchild_10_transform_rotate_30deg/ghzhwqu/?context=3) they spill directly into text, as only single level of `^superscripts` is now allowed across entire reddit:
![Screenshot_2021-01-04 r css_irl - Comment by u tomtheimpaler on ” window nth-child( 10 ) { transform rotate( 30deg ); trans _20210104141230](https://user-images.githubusercontent.com/59403389/103543723-476ca080-4e9f-11eb-846f-3bf1a275a75f.png)

the solution would be to just use scoped `<sup>`: `^(this entire text is superscripted, [link](/link) too)`
test: https://new.reddit.com/user/dym_sh/comments/kq9n3n/this_is_a_superscripttest_post/

**Comment by Lachcim** [comment]
Thanks for your input! Unfortunately, I'm afraid this solution doesn't work on old.reddit.com:

![Screenshot 2021-01-04 190453](https://user-images.githubusercontent.com/15709471/103565070-f3be7f00-4ebf-11eb-94c9-36f69433d1a8.png)

The disparity between various versions of Reddit and their respective Markdown parsers has been a source of issues for a while now, in particular, our issue #5. /r/badcode [even has a bot](https://old.reddit.com/r/badcode/comments/kl4ao8/friend_asked_me_why_every_grade_is_an_invalid/ghabyxb/) going around warning of this very problem.

I've been on the lookout for a universal solution for a while now, if you can think of any - please do let me know.

**Comment by ghost** [comment]
yeah, is there an ETA for planned obsolescence of old.reddit? they archived those repos long time ago, no way its coming back

**Comment by ghost** [comment]
did some more testing, it seems just putting sups on each word, but outside of `^^^[links](/links)` – is the only universally respectful way

<img width=30% src='https://user-images.githubusercontent.com/59403389/103568882-a691db80-4ec6-11eb-8edd-5f2a57eaa0e4.png'> <img width=30% src='https://user-images.githubusercontent.com/59403389/103569038-e658c300-4ec6-11eb-9bc3-5dc21d8ed189.png'>

**Comment by Lachcim** [comment]
Thanks! There is still an issue with superscripting subreddit links but this is clearly beyond our control.

![Screenshot 2021-01-04 204941](https://user-images.githubusercontent.com/15709471/103573413-7b12ef00-4ece-11eb-8eec-8bab2114e57d.png)

I'd rather not create a dedicated hyperlink because of how various clients handle those.

**Comment by ghost** [comment]
related: started dedicated [markdown-tests](https://github.com/dym-sh/markdown-tests/) suite, as it happens often enough, that it needs to be a dedicated repo with cross-linking to different uses and implementations.

(prolly there are already other projects for the same task, but alas)
